### ISSUE TITLE
Error messages using @assert need to be turned into normal exceptions

### ISSUE THREAD

**Issue by akabla** [JuliaRheology/RHEOS.jl#105]
We deal with many errors in parameters with an `@assert` macro. For instance:
 `   @assert hastime(d) "Data without time information cannot be resampled."  `

`@assert` may be disabled with certain optimisations, and therefore not appropriate for this usage.
[https://docs.julialang.org/en/v1/base/base/#Base.@assert](https://docs.julialang.org/en/v1/base/base/#Base.@assert)

It would be more appropriate to reserve `@assert` for debugging purposes only, and use proper exceptions for error message supposed to be helpful to the user.

This page may be useful:
[https://scls.gitbooks.io/ljthw/content/_chapters/11-ex8.html](https://scls.gitbooks.io/ljthw/content/_chapters/11-ex8.html)

**Comment by moustachio-belvedere** [comment]
Important issue, but I think this is duplicated:

https://github.com/JuliaRheology/RHEOS.jl/issues/81

**Comment by akabla** [comment]
indeed! let me close this here - no need to have it twice.
