### ISSUE TITLE
RheoModel struct rewrite

### ISSUE THREAD

**Issue by akabla** [JuliaRheology/RHEOS.jl#106]
To inform future updates on the RheoModel struct, I made some more benchmarks to compare different options.

The file is [there :RheoBenchAndTest](https://github.com/JuliaRheology/RheoBenchAndTest/blob/55991962de4cd06c37f0ca33560344119c1f8d4c/20210408_FW_KwdArg_benchmark.jl).

After lots of trial and error (and learning...), I could get the functions with keyword parameters to be nearly as efficient as the function wrappers. I could also improve a bit the function wrappers compared to the current implementation, but not by much.

The data is pasted below for reference. 4 implementations are compared:
- using or not struct parameters to integrate the function type to the struct fields, and 
- using or not vectorised forms of the modulus function/expression. 

There is now a lot of consistency across the different methods tested, so I think this has converged to a satisfactory point.

Some observations. 

Getting the keyword argument functions to work well with vector parameters (as needed y NLopt) was a bit tricky and required some care. Keyword arguments are very effective on their own, and a great way to handle functions in Julia, but creating them from vectors not very efficient. This leads to a high cost for the scalar function with vector parameters (RheoModelClass). For the vector time function `_Ga`, the effect is less visible as long as the conversion of the parameters is done only once, before the vectorized operation. This sorted the dreadful performance I previously reported. When the parameters are set (RheoModel), the performance of the keyword parameter functions is probably as good as it can be. Overall this could be a workable solution as long as vector operations are mostly used - which is the case with NLopt I believe.

Function wrappers built from expressions perform overall very well and very consistently. The results show that the current implementation is effective. It's been difficult to change much the performance compared to where we are, so the behaviour seems quite robust. But this all relies on FW being well maintained and tested alongside Julia base on the long term. We know this represents a vulnerability based on experience last year.

For some reason, the scalar versions of the moduli for both function wrappers and keyword args parameters benefit from having their type set in the declaration of the RheoModel struct (using the parametric struct construct). This seems to help Julia optimize the code when they are called from a function, resulting in a significant improvement of the execution speed.

Applying the modulus function to a time array doesn't benefit much from specifying the function type in the struct. 

Using a vectorized expression or function helps significantly vector operations with free parameters, being ~15% faster than a broadcast on the scalar function when using expressions and FW, which I find surprising. It is possible that Julia detects better in this case the constant value of the parameters for all time `t`. There is no visible penalty when these vectorized expressions are applied to scalar values. So we should consider doing this for all the models in Rheos.

This is overall a useful exercise, which gives us two decent approaches to work with. The next step is to make the RheoModel / RheoModelClass structs work with either FW or functions (following the example used in the benchmark file) and allow two different function formats internally, expression based FW, and modulus functions with keyword arguments, which have their strength too. All our models are currently defined with expressions and FW, and there is no reason to change this right now. If needed in the future, it would be an easy step to migrate to julia functions, and could be done for a subset of models or even functions within models. Hopefully, no more hack as we did earlier in #61 ...

Non typed functions fields in the struct | Parametric struct with typed functions fields | Non typed functions fields in the struct | Parametric struct with typed functions fields
-- | -- | -- | --
struct RheoModel...      _G     _Ga | struct RheoModel{GT, GaT}   ...   _G::GT     _Ga::GaT | struct RheoModel...      _G     _Ga | struct RheoModel{GT, GaT}   ...   _G::GT     _Ga::GaT
With scalar expressions for FW and keyword params | With scalar expressions for FW and keyword params | With vectorized expressions for FW and keyword params | With vectorized expressions for FW and keyword params
G=quote k*exp((-k/η)*t) end | G=quote k*exp((-k/η)*t) end | Ga = quote k.*exp.((-k./η).*t) end | Ga = quote k.*exp.((-k./η).*t) end
  |   |   |  
  |   |   |  
RheoModel function on scalar time values with free params | RheoModel function on scalar time values with free params | RheoModel function on scalar time values with free params | RheoModel function on scalar time values with free params
  |   |   |  
Function wrappers | Function wrappers | Function wrappers | Function wrappers
Direct call:   251.931 ns (3 allocations: 144 bytes) | Direct call:   251.354 ns (3 allocations: 144 bytes) | Direct call:   257.405 ns (3 allocations: 144 bytes) | Direct call:   255.452 ns (3 allocations: 144 bytes)
In function:   247.000 ns (3 allocations: 128 bytes) | In function:   66.146 ns (2 allocations: 112 bytes) | In function:   241.387 ns (3 allocations: 128 bytes) | In function:   66.502 ns (2 allocations: 112 bytes)
  |   |   |  
Scalar function with keyword params | Scalar function with keyword params | Scalar function with keyword params | Scalar function with keyword params
Direct call:   981.357 ns (12 allocations: 448 bytes) | Direct call:   1.008 μs (13 allocations: 496 bytes) | Direct call:   985.000 ns (12 allocations: 448 bytes) | Direct call:   1.004 μs (13 allocations: 496 bytes)
In function:   985.455 ns (12 allocations: 432 bytes) | In function:   951.955 ns (11 allocations: 416 bytes) | In function:   972.000 ns (12 allocations: 432 bytes) | In function:   954.842 ns (11 allocations: 416 bytes)
  |   |   |  
Scalar function with array params | Scalar function with array params | Scalar function with array params | Scalar function with array params
Direct call:   90.044 ns (3 allocations: 144 bytes) | Direct call:   97.119 ns (3 allocations: 128 bytes) | Direct call:   90.979 ns (3 allocations: 144 bytes) | Direct call:   99.985 ns (3 allocations: 128 bytes)
In function:   81.165 ns (3 allocations: 128 bytes) | In function:   58.173 ns (2 allocations: 112 bytes) | In function:   81.485 ns (3 allocations: 128 bytes) | In function:   58.253 ns (2 allocations: 112 bytes)
  |   |   |  
Vector function with array params | Vector function with array params | Vector function with array params | Vector function with array params
Direct call:   148.272 ns (5 allocations: 336 bytes) | Direct call:   162.209 ns (5 allocations: 320 bytes) | Direct call:   152.856 ns (5 allocations: 336 bytes) | Direct call:   163.914 ns (5 allocations: 320 bytes)
In function:   144.048 ns (5 allocations: 320 bytes) | In function:   125.924 ns (4 allocations: 304 bytes) | In function:   143.605 ns (5 allocations: 320 bytes) | In function:   119.617 ns (4 allocations: 304 bytes)
  |   |   |  
  |   |   |  
RheoModel function on array time values with free params | RheoModel function on array time values with free params | RheoModel function on array time values with free params | RheoModel function on array time values with free params
  |   |   |  
Function wrappers | Function wrappers | Function wrappers | Function wrappers
Direct call:   8.257 μs (3 allocations: 8.12 KiB) | Direct call:   8.209 μs (3 allocations: 8.12 KiB) | Direct call:   6.949 μs (3 allocations: 8.12 KiB) | Direct call:   7.592 μs (3 allocations: 8.12 KiB)
In function:   8.208 μs (2 allocations: 8.09 KiB) | In function:   7.876 μs (2 allocations: 8.09 KiB) | In function:   6.903 μs (2 allocations: 8.09 KiB) | In function:   7.499 μs (2 allocations: 8.09 KiB)
  |   |   |  
Scalar function with keyword params | Scalar function with keyword params | Scalar function with keyword params | Scalar function with keyword params
Direct call:   8.849 μs (13 allocations: 8.47 KiB) | Direct call:   9.064 μs (14 allocations: 8.52 KiB) | Direct call:   8.712 μs (11 allocations: 8.41 KiB) | Direct call:   8.869 μs (12 allocations: 8.45 KiB)
In function:   8.809 μs (12 allocations: 8.44 KiB) | In function:   8.986 μs (12 allocations: 8.44 KiB) | In function:   8.223 μs (10 allocations: 8.38 KiB) | In function:   8.800 μs (10 allocations: 8.38 KiB)
  |   |   |  
Scalar function with array params | Scalar function with array params | Scalar function with array params | Scalar function with array params
Direct call:   7.958 μs (3 allocations: 8.12 KiB) | Direct call:   8.505 μs (3 allocations: 8.11 KiB) | Direct call:   8.158 μs (3 allocations: 8.12 KiB) | Direct call:   8.064 μs (3 allocations: 8.11 KiB)
In function:   8.127 μs (2 allocations: 8.09 KiB) | In function:   8.455 μs (2 allocations: 8.09 KiB) | In function:   8.303 μs (2 allocations: 8.09 KiB) | In function:   8.074 μs (2 allocations: 8.09 KiB)
  |   |   |  
Vector function with array params | Vector function with array params | Vector function with array params | Vector function with array params
Direct call:   7.202 μs (3 allocations: 8.12 KiB) | Direct call:   7.543 μs (3 allocations: 8.11 KiB) | Direct call:   7.223 μs (3 allocations: 8.12 KiB) | Direct call:   7.509 μs (3 allocations: 8.11 KiB)
In function:   7.183 μs (2 allocations: 8.09 KiB) | In function:   7.476 μs (2 allocations: 8.09 KiB) | In function:   7.170 μs (2 allocations: 8.09 KiB) | In function:   7.478 μs (2 allocations: 8.09 KiB)
  |   |   |  
  |   |   |  
RheoModel function on scalar time values with fixed params | RheoModel function on scalar time values with fixed params | RheoModel function on scalar time values with fixed params | RheoModel function on scalar time values with fixed params
  |   |   |  
Function wrappers | Function wrappers | Function wrappers | Function wrappers
Direct call:   64.532 ns (2 allocations: 48 bytes) | Direct call:   66.522 ns (2 allocations: 48 bytes) | Direct call:   64.928 ns (2 allocations: 48 bytes) | Direct call:   61.536 ns (2 allocations: 48 bytes)
In function:   49.452 ns (2 allocations: 32 bytes) | In function:   33.186 ns (1 allocation: 16 bytes) | In function:   51.087 ns (2 allocations: 32 bytes) | In function:   31.375 ns (1 allocation: 16 bytes)
  |   |   |  
Scalar function with keyword params | Scalar function with keyword params | Scalar function with keyword params | Scalar function with keyword params
Direct call:   60.944 ns (2 allocations: 48 bytes) | Direct call:   78.784 ns (3 allocations: 96 bytes) | Direct call:   62.737 ns (2 allocations: 48 bytes) | Direct call:   77.571 ns (3 allocations: 96 bytes)
In function:   50.015 ns (2 allocations: 32 bytes) | In function:   28.608 ns (1 allocation: 16 bytes) | In function:   50.066 ns (2 allocations: 32 bytes) | In function:   27.892 ns (1 allocation: 16 bytes)
  |   |   |  
Scalar function with array params | Scalar function with array params | Scalar function with array params | Scalar function with array params
Direct call:   64.081 ns (2 allocations: 48 bytes) | Direct call:   76.860 ns (3 allocations: 64 bytes) | Direct call:   63.483 ns (2 allocations: 48 bytes) | Direct call:   78.460 ns (3 allocations: 64 bytes)
In function:   53.483 ns (2 allocations: 32 bytes) | In function:   30.396 ns (1 allocation: 16 bytes) | In function:   53.101 ns (2 allocations: 32 bytes) | In function:   33.352 ns (1 allocation: 16 bytes)
  |   |   |  
Vector function with array params | Vector function with array params | Vector function with array params | Vector function with array params
Direct call:   128.859 ns (4 allocations: 240 bytes) | Direct call:   135.419 ns (5 allocations: 256 bytes) | Direct call:   123.265 ns (4 allocations: 240 bytes) | Direct call:   140.695 ns (5 allocations: 256 bytes)
In function:   107.906 ns (4 allocations: 224 bytes) | In function:   93.931 ns (3 allocations: 208 bytes) | In function:   114.592 ns (4 allocations: 224 bytes) | In function:   91.874 ns (3 allocations: 208 bytes)
  |   |   |  
  |   |   |  
RheoModel function on array time values with fixed params | RheoModel function on array time values with fixed params | RheoModel function on array time values with fixed params | RheoModel function on array time values with fixed params
  |   |   |  
Function wrappers | Function wrappers | Function wrappers | Function wrappers
Direct call:   7.500 μs (2 allocations: 8.03 KiB) | Direct call:   7.204 μs (2 allocations: 8.03 KiB) | Direct call:   6.822 μs (2 allocations: 8.03 KiB) | Direct call:   7.164 μs (2 allocations: 8.03 KiB)
In function:   7.446 μs (1 allocation: 8.00 KiB) | In function:   7.139 μs (1 allocation: 8.00 KiB) | In function:   7.114 μs (1 allocation: 8.00 KiB) | In function:   7.130 μs (1 allocation: 8.00 KiB)
  |   |   |  
Scalar function with keyword params | Scalar function with keyword params | Scalar function with keyword params | Scalar function with keyword params
Direct call:   7.506 μs (2 allocations: 8.03 KiB) | Direct call:   7.853 μs (3 allocations: 8.08 KiB) | Direct call:   7.167 μs (2 allocations: 8.03 KiB) | Direct call:   7.795 μs (3 allocations: 8.08 KiB)
In function:   7.467 μs (1 allocation: 8.00 KiB) | In function:   7.758 μs (1 allocation: 8.00 KiB) | In function:   7.152 μs (1 allocation: 8.00 KiB) | In function:   7.741 μs (1 allocation: 8.00 KiB)
  |   |   |  
Scalar function with array params | Scalar function with array params | Scalar function with array params | Scalar function with array params
Direct call:   7.987 μs (2 allocations: 8.03 KiB) | Direct call:   8.104 μs (3 allocations: 8.05 KiB) | Direct call:   7.913 μs (2 allocations: 8.03 KiB) | Direct call:   8.460 μs (3 allocations: 8.05 KiB)
In function:   7.887 μs (1 allocation: 8.00 KiB) | In function:   7.838 μs (1 allocation: 8.00 KiB) | In function:   7.886 μs (1 allocation: 8.00 KiB) | In function:   8.015 μs (1 allocation: 8.00 KiB)
  |   |   |  
Vector function with array params | Vector function with array params | Vector function with array params | Vector function with array params
Direct call:   7.166 μs (2 allocations: 8.03 KiB) | Direct call:   7.542 μs (3 allocations: 8.05 KiB) | Direct call:   7.188 μs (2 allocations: 8.03 KiB) | Direct call:   7.504 μs (3 allocations: 8.05 KiB)
In function:   7.142 μs (1 allocation: 8.00 KiB) | In function:   7.431 μs (1 allocation: 8.00 KiB) | In function:   7.806 μs (1 allocation: 8.00 KiB) | In function:   7.451 μs (1 allocation: 8.00 KiB)
  |   |   |  
  |   |   |

**Comment by moustachio-belvedere** [comment]
As promised, spent some time this morning making some additional benchmarks. I wanted to test things as close to 'representative' as possible. Of course, data sets will vary greatly. Feel free to play around with the numbers and/or moduli used if you want to.

Also, if I haven't made something efficient on the functionwrappers side, please let me know so I can run updated tests.

https://github.com/JuliaRheology/RheoBenchAndTest/blob/master/20210410_fwclosures_additional.jl 

According to my benchmarks, for representative data samples and moduli:
**named tuple arguments add ~6% overhead for simple modulus (non-fractional), and around ~3% overhead for complex modulus (fractional).**

Also:

> Using a vectorized expression or function helps significantly vector operations with free parameters, being ~15% faster than a broadcast on the scalar function when using expressions and FW, which I find surprising. It is possible that Julia detects better in this case the constant value of the parameters for all time t. There is no visible penalty when these vectorized expressions are applied to scalar values. So we should consider doing this for all the models in Rheos.

Not sure I understood completely on this, maybe we can discuss later. But if I did get your meaning correctly, I'm not sure about that? I rehashed some older benchmarks I did and tested on Julia 1.6:

https://github.com/JuliaRheology/RheoBenchAndTest/blob/master/20210410_broadcasting.jl

It doesn't seem to matter whether the broadcast happens internally or externally, same result. Loops have a very slight improvement.

If I remember correctly, I may have tried something similar with functionwrappers a while ago. In that case, having the broadcast internally (as you do for Ga) was important. Maybe Julia compiler isn't smart enough to optimise an externally broadcast functionwrapper in an optimal way.

Heading out for 2/3 hours now, but happy to chat properly later, or another day, if you'd like to.

**Comment by akabla** [comment]
Hi Louis. Thanks, yes, let's have a chat when you are back.

I updated your example file on broadcasting to include the vectorized expression in the test. The key is to dot every single operator, including `.=` if you are storing in another variable; but we don't need that here, we can return the result directly. As you will see, it does improve visibly the performance one the benchmark:
  1.587 ms (2 allocations: 781.39 KiB)  VS   1.880 ms (2 allocations: 781.39 KiB)
So there is something clever going on under the hood.

Apart from that, your benchmark on FW vs functions with kwd arguments is consistent with what I did. The more operations we add in addition to the function calls, the more the performance differences get blurred at the end. The bottom line is that both approaches seem suitable from a performance point of view.

Talk to you later.

**Comment by akabla** [comment]
The revamp of the RheoModel is done in terms of the code, see #111 (mostly 5de623b). As always, lots of edge cases I did not think about. One of them is the fact that the macro @. does not work with multiline expressions. It also seems to struggle with the most complex expressions, for instance, complex modulus of the Fract Maxwell model. For any expression provided, we now test if the expression is multiline, and only use @. if this is a single line. I learned a few other things about manipulating expressions on the way. Changes are non-breaking, except with a RheModelClass is declared by the user. Then parameter symbols have to be provided as a tuple rather than an array. We had many of these in the test file for processing.jl!

All tests are passing, including the doc which helped identify an error too. The benchmark shows the same level of performance, only slightly better for case where @. is used, as expected. I now need to clean up commented code, add more tests for the helper functions, and document the new struct.

Feel free to have a look at the draft pull request #111 and make comments there. Please keep it open as codecov helps me identify where tests are needed.

The code is also ready to take easily two changes:

- flags are in place to indicate the need to work with the ramp response and the second derivative of the strain/stress. Nothing done yet in processing.jl, and no changes have been made to the model definitions either. Ideally, no moduli function will contain any singularity after this.
- turn expressions involving variable s rather than t for the moduli into calls to inverse Laplace, so that we do not need to specify the call to inverse Laplace in the declaration of the model expressions - it will be done by the RheoModel constructor before building the moduli functions. All the handles are in place in the constructor and _buildmoduli helper functions.

If we want to use functions instead of function wrappers in future, we now only need to introduce functions _buildmoduli_t/ω that take Function as parameter and do the relevant bindings, as the examples metionned above. We also need to allow the various moduli fields to have arbitrary types, rather than function wrappers.
