### ISSUE TITLE
Do we need really python to generate the doc's graphs?

### ISSUE THREAD

**Issue by akabla** [JuliaRheology/RHEOS.jl#161]
Following some investigations for issue #160 , I removed the eye candy using python and PyCall to center one of the plots. I simply placed the three plots on top of each other. It works better for mobile devices, and keeps the documentation simpler to maintain. 

@alebonfanti , @moustachio-belvedere , any views?

**Comment by moustachio-belvedere** [comment]
Looks fine to me! Thanks Alexandre

**Comment by moustachio-belvedere** [comment]
BTW, I'm not sure why but there's some installation output showing in the newly built docs that wasn't there before:
https://juliarheology.github.io/RHEOS.jl/dev/examples/

**Comment by akabla** [comment]
Thanks Louis. That's new indeed.

**Comment by alebonfanti** [comment]
Looks good to me as well! Thanks!

**Comment by akabla** [comment]
In fact, I'm wondering if we should not switch to Gadfly or something similar for the tutorials. It may also help with #163.

**Comment by alebonfanti** [comment]
what do you think of  Plots.jl?

**Comment by akabla** [comment]
Plots is great, but seems to be big - with many different backends. I was thinking about a package written in pure julia to remove dependencies as much as possible. Makie looks actually good.

**Comment by moustachio-belvedere** [comment]
I don't have a preference but good to note the main advantage of PyPlot is that it is more familiar to people with a Python background

**Comment by akabla** [comment]
To note that there is also a package called PythonPlot, based on PythonCall, an alternative to PyCall.
I'm closing this as this was all triggered by issues with the doc generation, which is now working fine. We can revisit this later if needed.
