### ISSUE TITLE
boltzconvolve_nonsing called in modelpredict, but does not exist anymore

### ISSUE THREAD

**Issue by akabla** [JuliaRheology/RHEOS.jl#18]
Here is the line:    
    convolved = boltzconvolve_nonsing(modulus, t_zeroed, dt, dcontrolled)

Any idea? what function should we call?

I'm working on the log at the moment on my machine. please do not fix, just let me know the patch so that I can fix it and test it on mine before I push my changes.

thanks, 

a

**Comment by moustachio-belvedere** [comment]
I fixed by mistake, so I then reverted with `git revert`.

For the fixing commit see: 2fc34aebc52745f6211034d2eb63fd927f1ae994

**Comment by moustachio-belvedere** [comment]
I made a few other small changes to fix the tests etc and add warning to `nanremove`. 

Feel free to `git revert` and then add in manually again later if it is causing irritating merge conflict issues.

**Comment by akabla** [comment]
Great, thanks. Made the correction. Seems fine now.
