### ISSUE TITLE
Operators missing on Frequency data

### ISSUE THREAD

**Issue by akabla** [JuliaRheology/RHEOS.jl#20]
Should be straight forward based on the code for real time data.

**Comment by moustachio-belvedere** [comment]
as in +/-/* ? Does that make sense for frequency data? If it will be useful to people then happy for it to be added -- but I can't see myself using it.

**Comment by akabla** [comment]
You are right, not useful for freq domain as we use store there the complex modulus, not input/output.
Issue closed!
