### ISSUE TITLE
Need show operator for RheoLog

### ISSUE THREAD

**Issue by akabla** [JuliaRheology/RHEOS.jl#21]
It looks quite messy in the REPL when these objects are returned.

**Comment by moustachio-belvedere** [comment]
Thanks I noticed you have already done the one for RheoTimeData, it looks nice.

I have modified your solution for RheoTime Data for RheoFreqData, commit 18cc9645289295c0f514f28ea00b6721a25c54f1 .

So the only one that is left is RheoLog.

**Comment by akabla** [comment]
This was helpful:
https://discourse.julialang.org/t/extending-base-show-for-array-of-types/31289
