### ISSUE TITLE
@enum TimeDataType and FreqDataType names are confusing

### ISSUE THREAD

**Issue by moustachio-belvedere** [JuliaRheology/RHEOS.jl#22]
I think there is potential for a number of renamings:

`strain_only` -> could be something like `strain_time` as it includes strain and time.
`stress_only` -> could be something like `stress_time` as it includes strain and time.
`strain_and_stress` -> could be something like `full` as it includes all data fields.

`frec_only` -> should probably be `freq_only`, the c looks like a mispelling?

Note that I don't mind what they are changed to, but just wanted to point out which ones are confusing and why.

**Comment by akabla** [comment]
Happy with clarifying this, I see your point.

But maybe we can talk about it together later on. I'd prefer calling them
"time", "strain", "stress" and "stress_strain", but these keywords may be
also used for other things.

frec_only is a typo indeed! embarrassing...

**Comment by moustachio-belvedere** [comment]
Sure happy to discuss the time data types further.

I amended the frequency data type so this issue is partially concluded, see commit e95d27159bf7f611cbf328fc62e1fb0e6871cb8e

**Comment by moustachio-belvedere** [comment]
I have been playing with ideas in my head for a while now and I can't settle on anything that I think is clearer. (I agree, using `time` `stress` and `stress_strain` would be clear but probably not a good use of the namespace.)

Closing for now.
