### ISSUE TITLE
should `extract` for RheoFreqData take a FreqDataType

### ISSUE THREAD

**Issue by moustachio-belvedere** [JuliaRheology/RHEOS.jl#23]
At the moment, `extract` for `RheoTimeData` types needs a `TimeDataType` argument which makes sense because you might want to extract time, or time and stress, or time and strain.

However, `extract` for `RheoFreqData` types always just extracts the frequency vector as it doesn't make any sense to ever have Gp without Gpp and vice versa. 

So when using `extract` for `RheoFreqData`, the second argument of `FreqDataType` is completely redundant.

I can think of a few options:

- We keep behavior as it is

- Remove second argument for `RheoFreqData` types

- Rename the `RheoFreqData` method `extractfrequency` or something more specialised so it is clear from the function name what it does, and remove the redundant second argument.

**Comment by akabla** [comment]
Hi Louis,

I agree that this is odd. We treated the frec data as we did with time
data, but they are fundamentally different.

We probably still need a function to extract the freq vector as a new
RheoFreqData. We may also need a new generator function to create Gp and
Gpp from omega. Not sure if this exists.

I am happy with renaming the function extractfrequency. Maybe we should
then rename the other ones extracttime, extractstrain (t & epsilon) and
extractstress (t & sigma).

**Comment by akabla** [comment]
I'm wondering if it would not be simpler to rename all extract functions for consistency:

```
extracttime
extractstrain
extractstress
extractfreq
```

I think it would make the code cleaner and simpler to read for the user, and for us. Most of the code of the extract function is spent working out which parameter to extract.

Note: these functions are currently defined in processing.jl

**Comment by moustachio-belvedere** [comment]
Sounds good to me!

**Comment by akabla** [comment]
The functions `extract` are still there to avoid breaking changes, but now deprecated. To be removed with version 1.0.

**Comment by akabla** [comment]
Need to include new functions in API
