### ISSUE TITLE
lots of non-code comments in definitions.jl need addressing

### ISSUE THREAD

**Issue by moustachio-belvedere** [JuliaRheology/RHEOS.jl#26]
In definitions.jl there are lots of comments that seem to be works-in-progress or reminders to do things. I don't know what they all mean, and which are redundant, so I cannot delete them.

If they are comments that explain how to do things they should probably be converted into a proper docstring attached to the related function or moved to documentation.

If they are reminders for things that still need to be done they should be probably be made into an issue here.

The rest can probably be deleted?

**Comment by akabla** [comment]
some clean-up needed indeed.
Please do not delete for now.
A good number of these now belong to the issue section of the github page.

**Comment by moustachio-belvedere** [comment]
I hope it is OK but in preparation for testing I did a small amount of 'housekeeping' on definitions.jl, I can revert the commit if you want if you are unhappy with anything. 

Main purpose was to organise the functions in a sensible order (as I like to have the testing functions in the same order).  In doing so, I did remove one comment that seems obvious now:

```
#
#   Function called when a RheoTimeData struct is returned to the REPL
#
```
for a base.show overload for `RheoTimeData`.

And also replaced 

```
#
#  Internal functions to regenerate data from a log
#
```
with a similar header (also used same header style to group the other related functions).

See this commit for more info: be05eb4fb765ef9b7cc0f212da87dd7e7a90b44c

**Comment by moustachio-belvedere** [comment]
@akabla  are you happy for me to wrap this up? Anything that is a comment about something that needs to be done I will add as a GitHub issue. Anything else I will try and slot in next to relevant bits of code.

**Comment by akabla** [comment]
Thanks Louis, yes please proceed, I can't handle it right now.
Good idea to place all that as issues on github, this is where it belongs!

**Comment by moustachio-belvedere** [comment]
OK I think this is neat enough now. Closing issue.
