### ISSUE TITLE
Should example notebook code work in a normal Julia interpreter?

### ISSUE THREAD

**Issue by grantbruer** [JuliaRheology/RHEOS.jl#37]
I was trying to follow along with the burgers.ipynb example by running the code snippets directly in a Julia interpreter, and I found out that example code is not valid Julia. It runs fine in the notebook because IJulia modifies the variable scoping to be easier to use. (see https://github.com/JuliaLang/IJulia.jl#opting-out-of-soft-scope)

Specifically, the code below (which is repeated in other example notebooks) doesn't work in standard Julia because the for-loop has a different variable scope, so it gets mad and says that `models` hasn't been defined.
```
julia> models = Vector{RheoModel}()
0-element Array{RheoModel,1}

julia> # plot moduli for varying k₁
       for (i,k) in enumerate([0.5, 1.0, 2.0])
           
           models = vcat(models,RheoModel(BurgersLiquid,(η₁ = 1, k₁ = k, η₂ = 1, k₂ = 1)))
        
       end
ERROR: UndefVarError: models not defined
Stacktrace:
 [1] top-level scope at ./REPL[12]:4
```

This could be changed to work in standard Julia by specifying that the left-hand side `models` is a global variable:

```
models = Vector{RheoModel}()

# plot moduli for varying k₁
for (i,k) in enumerate([0.5, 1.0, 2.0])
    global models = vcat(models,RheoModel(BurgersLiquid,(η₁ = 1, k₁ = k, η₂ = 1, k₂ = 1))) 
end
```

or by not assigning to `models`, so that it knows that `models` is not a local for-loop variable:

```
models = Vector{RheoModel}()

# plot moduli for varying k₁
for (i,k) in enumerate([0.5, 1.0, 2.0])
    push!(models,RheoModel(BurgersLiquid,(η₁ = 1, k₁ = k, η₂ = 1, k₂ = 1))) 
end
```

This can be marked as "Seeking opinions" because I'm not really sure if this needs to be changed, but I still wanted to point it out. There's an argument that IJulia provides this functionality to make the code easier to write and understand, so it should be used. But if anyone tries to run the example code without using Jupyter, then they'll run into this issue.

**Comment by moustachio-belvedere** [comment]
Thanks a lot for pointing that out Grant. Alessandra and I just had a chat about it and we will go for the `push!` approach as it seems a little more generic. Should be updated soon.

**Comment by akabla** [comment]
Thanks so much Grant @gbruer15 for raising this. Definitely something to address. 
I was not aware scoping rules were different with IJulia, so you also taught me something!

Thanks Louis and Ale for taking the lead on this. I agree that the push! approach seems more suitable.

@moustachio-belvedere @ab2425

**Comment by alebonfanti** [comment]
Thanks a lot Grant @gbruer15 for your help. That is an important point.
For fixing commit see: a736997eed62aeb3f3a4bd8f82ba154f18d0e1d4
