### ISSUE TITLE
[JOSS] Minor Markdown Formatting

### ISSUE THREAD

**Issue by HaoZeke** [JuliaRheology/RHEOS.jl#38]
Hi. This is part of the JOSS review https://github.com/openjournals/joss-reviews/issues/1700. I was wondering if the image in the paper might be made a bit smaller to improve the overall pdf formatting. Specifically, at the moment, there is almost over half a page of whitespace before Figure one, as shown visually in the screenshot.
![image](https://user-images.githubusercontent.com/4336207/64467811-42c49a80-d13a-11e9-959c-a0327130dca0.png)

**Comment by akabla** [comment]
Thanks very much Rohit, I agree with you, that is not optimal. I tried to make the figure more compact, but this does not really solve the problem on its own. We need to learn a bit more about how JOSS handles figure sizes and placement. We'll investigate next week!

**Comment by HaoZeke** [comment]
Oh in that case, since I believe @whedon (and therefore JOSS) uses pandoc internally, you could play around with the [following syntax](https://pandoc.org/MANUAL.html#images):

```md
![](file.jpg){ width=50% }
```
Which essentially becomes:
```latex
\includegraphics[width=0.5\textwidth,height=\textheight]{file.jpg}
```
I'll continue with the rest of the review in the meantime.

**Comment by HaoZeke** [comment]
As of https://github.com/JuliaRheology/RHEOS.jl/commit/cf4a2b76208e24c692c3564d1281e8ef97ca3b1d
This has been resolved very nicely. Thanks!

**Comment by akabla** [comment]
Fantastic! thanks so much Rohit.
It looks much better now. I'll play a bit more with the figure size later on.
