### ISSUE TITLE
Documenting Doc Building and Test Running

### ISSUE THREAD

**Issue by grantbruer** [JuliaRheology/RHEOS.jl#39]
Is there documentation somewhere on how to build the docs and run the tests?

Just by reading through all the files, it looks like `julia docs/make.jl` and `julia test/runtests.jl` will do the job, but I think it would be helpful if this was officially documented somewhere.

**Comment by akabla** [comment]
Dear Grant,

yes, Louis (@moustachio-belvedere) wrote something to train the rest of the team a while back, but the document is not in this repo at this point. Good idea to extract relevant sections and attach it to the main Rheos repo. We'll look into that too. Thanks.

**Comment by moustachio-belvedere** [comment]
Thanks Grant,

Yes both are documented in this repository: https://github.com/JuliaRheology/RheoHelpDocs but as Alexandre mentioned, we will see where we can add in some more info about locally building documentation and local testing in the main documentation. 

Or alternatively, do you think it might be favourable to point to that repository from the main RHEOS documentation? That way the meta-documentation has a clean separation from the rest of the docs, but is still contained within the JuliaRheology umbrella organization.

And yes you are right that `julia docs/make.jl` and `julia test/runtests.jl` build the docs and run the tests respectively. In `pkg` mode (you can enter by pressing `]` in the REPL) you can also use the command `test RHEOS` for testing.

@akabla the documentation system is a little more complicated now that Ale has added in the nice jupyter-notebook-to-markdown feature. I will discuss a bit more with her later today.

**edit:** On further thoughts, I am leaning towards adding a link the meta-documentation in the 'Contributing to RHEOS' section of the documentation, Ale also agrees with this. Would be good to know what you both think @akabla @gbruer15.

**Comment by grantbruer** [comment]
Adding the link to the other repo sounds good to me.

**Comment by moustachio-belvedere** [comment]
Great, that's wrapped up by commit 3719566c54e11f1e24bb9177c3d1a478952ffd7e

There's a separate issue on the meta-documentation repository to update it slightly for the more complicated build system.
