### ISSUE TITLE
Formatting problem due to underscores in documentation

### ISSUE THREAD

**Issue by grantbruer** [JuliaRheology/RHEOS.jl#40]
The API page has italics in a lot of places (e.g., 
https://juliarheology.github.io/RHEOS.jl/latest/API/#RHEOS.extract) where it should have underscores. 

This problem also occurs in the Julia interpreter when getting the documentation for a function.
```julia
help?> extract
search: extract extrema

  extract(self::Union{RheoTimeData,RheoFreqData}, type::Union{TimeDataType,FreqDataType,Integer})

  Extract specific fields form RheoTimeData or RheoFreqData.

  Extract can copy one or more fields from a given RheoXData variable into a new RheoXData one. The
  fields that are copied are identified by the specified type of data. If self is a RheoTimeData,
  the type that can be extracted is timeonly (or 0), stressonly (or 1), strainonly (or 2). Note
  that strainandstress (or 3) is not allowed. If self is a RheoFreqData, the type that can be
  extracted is freqonly (or 0).
```
I'm guessing the underscores just need to be escaped somehow.

**Comment by akabla** [comment]
Thanks Grant for spotting this. We'll sort it out. 

Louis, Ale, maybe the most appropriate would be to display these words as inline code between back-ticks, e.g. `strain_only`?  @ab2425 @moustachio-belvedere

**Comment by moustachio-belvedere** [comment]
Thanks Grant and Alexandre. Yes I always try and do any programmatic reference in back ticks and that does indeed fix this issue. 

I have made the all the corrections (I think), please do let me know if I have missed any!
