### ISSUE TITLE
Examples notebook

### ISSUE THREAD

**Issue by adambeall** [JuliaRheology/RHEOS.jl#41]
I am just running the examples in (https://github.com/JuliaRheology/RHEOS.jl/blob/master/examples/examples.ipynb) and it looks like the plotting section for Example 2 (I think box 6) should have
`plot(maxwellD_predict.t,maxwellD_predict.σ, color = "red");`
instead of 
`plot(maxwell_predict.t,maxwell_predict.σ, color = "red");` (which is still plotting data from Example 1).

**Comment by alebonfanti** [comment]
Many thanks @adambeall for pointing this out. 
This should be fixed by a5377171e4f885947e7f9d01de9b6548f2c053ec
