### ISSUE TITLE
[JOSS] Citing NLopt

### ISSUE THREAD

**Issue by grantbruer** [JuliaRheology/RHEOS.jl#42]
Tiny correction: the paper refers to http://ab-initio.mit.edu/nlopt, but NLopt recommends using http://github.com/stevengj/nlopt as the url in the citation.

(source: https://nlopt.readthedocs.io/en/latest/Citing_NLopt/)

**Comment by moustachio-belvedere** [comment]
Thanks for pointing that out Grant. I think the URL has changed since I first put that reference in a year or so ago.

Updated in paper BIB file, README and documentation landing page.

Commit 625e5352469a21563ff573346f2043f6bb96148d
