### ISSUE TITLE
(JOSS) Documentation of Model Limitations

### ISSUE THREAD

**Issue by adambeall** [JuliaRheology/RHEOS.jl#43]
Would it be possible to clarify in the paper and perhaps the documentation exactly what the requirements and limitations for a custom rheological model are? It appears that you can create any linear viscoelastic rheology as long as relaxation and / or creep moduli can be provided or fitted. The paper mentions an “emphasis on linear rheological models” and shows an example of the hereditary integral form for linear viscoelastic materials, however as someone coming from a different field, I interpreted these as options rather than strict model prerequisites. If you agree, it would only take a few added words to make this clearer. 

On a related note, it may be useful to mention on the “Create Your Model” page in the documentation that it is also possible to build a model with only a creep modulus (provided only strain is predicted).

**Comment by akabla** [comment]
Thanks very much Adam @adambeall , this is a fair point indeed. 
You are right that at the moment linearity is a constraint of the methods implemented, although we have some plans to extend this in future. 
We will address this properly next week.

**Comment by akabla** [comment]
I have clarified the limitations of the current limitation of the library to the class of linear models, in the paper as well as in the [doc intro](https://juliarheology.github.io/RHEOS.jl/latest/).

Adam's comment regarding the "create your own model" section to follow.

**Comment by alebonfanti** [comment]
Thanks a lot Adam @adambeall. We have addressed the linearity limitation in the "create your own model" as well as the possibility of defining a model with only one modulus.

The following commits should have resolved this issue: 
f1114016ece9ebd35d75711d294785f78aa24e0c
2b67a912a59e31e5827d593cd2fff4b1ff2ebc98
41cfc646d34685379e38ff193d9d1ea5cd624f65

Please let us know if you have further queries.
