### ISSUE TITLE
[JOSS] References

### ISSUE THREAD

**Issue by HaoZeke** [JuliaRheology/RHEOS.jl#46]
Hi,
Very minor issue brought up by @whedon here, https://github.com/openjournals/joss-reviews/issues/1700#issuecomment-531591218

Would be happy to close once it has been addressed.
![image](https://user-images.githubusercontent.com/4336207/64926448-32d44700-d81b-11e9-9b8c-ff4d415450d0.png)

**Comment by akabla** [comment]
Thanks so much Rohit @HaoZeke for checking. 
Whedon is actually picking up a [review of the book](https://asmedigitalcollection.asme.org/appliedmechanics/article/44/2/364/388377/Creep-and-Relaxation-of-Nonlinear-Viscoelastic), and not the book itself. I can't find a doi for the book, and I'm not sure there is one. We'll look again.

**Comment by moustachio-belvedere** [comment]
Thanks for noting that @HaoZeke. Indeed, as @akabla mentioned, I can confirm that the DOI is a review of the book.

I did not notice it was a review at first and added in the DOI to the reference but Whedon still did not accept it so I looked a bit more closely. (This was during the pre-review https://github.com/openjournals/joss-reviews/issues/1681 , commit 331db27b80f47a6631fe4a952363ca9c766b7831 added it and then commit https://github.com/JuliaRheology/RHEOS.jl/commit/3409c4afa0e68d5b97ef4f4c8a884893ea3ca544 removed it once I had realised). I should have realised before as it is unusual for a book to have a DOI as far as I understand.

I will close the issue for now but please do let us know if you have any further queries on that.

Thanks again

**edit:** also worth noting that the paper.bib file has the full ISBN number for that book

**Comment by HaoZeke** [comment]
An thanks for clearing this up! Sorry I hadn't noticed it in the pre review.

**Comment by moustachio-belvedere** [comment]
No worries at all,
