### ISSUE TITLE
FunctionWrappers appear to be causing intermittent bugs

### ISSUE THREAD

**Issue by moustachio-belvedere** [JuliaRheology/RHEOS.jl#57]
For example https://travis-ci.org/JuliaRheology/RHEOS.jl/jobs/600348295

And I cannot get code coverage to work (Coverage.jl package). It always hits errors when it gets to the model tests that start using FunctionWrappers. The exact test it errors on seems to vary so it is clearly not test-specific, ~~the tests have always passed on my computer when run locally on Julia 1.1~~. The error messages always involve FunctionWrappers.

**Update:** When running the model tests only (the tests which call functions using FunctionWrappers) the test work locally, but running the entire RHEOS testing routine, it does crash when it gets to the model tests. Looks like a lower level bug with Julia or FunctionWrappers which needs to be resolved. May just be specific to 1.1 as 1.2 and Nightly tests are passing on Travis.

**Comment by moustachio-belvedere** [comment]
This seems to be Julia 1.1 specific bug. Running entire test suite on 1.2 is fine locally. v1.2 and nightly are both fine remotely.

Coverage is now working on 1.2.

Will update version constraints in Project.toml appropriately then close.

**Comment by moustachio-belvedere** [comment]
closed by e764f3329611a3346ce9488cc4f5008d48bbf103

**Comment by akabla** [comment]
Great news, thank you Louis for looking into it.
