### ISSUE TITLE
Documentation not up-to-date

### ISSUE THREAD

**Issue by alebonfanti** [JuliaRheology/RHEOS.jl#58]
I have just noticed that if I click on the button "stable" for the documentation, the version that is opened is without the changes we made during the revision process. The changes are shown only if the "dev" version is opened. 
I am unsure if this is how it is suppose to be. If so, in my opinion, it might create a bit of confusion.

**Comment by moustachio-belvedere** [comment]
It looks like the TagBot Github action pushes a tag to github but doesn't trigger a documentation build. I will look into this but will prioritise sorting the function wrapper bug https://github.com/JuliaRheology/RHEOS.jl/issues/61 for now as that is breaking many fractional models.

**Comment by moustachio-belvedere** [comment]
Wooops closed by mistake

**Comment by akabla** [comment]
I'm not sure that the dev version of the doc gets the latest version either. Is there a way to force the update of the doc?

**Comment by moustachio-belvedere** [comment]
The dev version was updating, but is not longer. I was trying to fix the 'stable' issue now but indeed you are right, even the dev version is not updating correctly now.

Looking at Travis, I can see that it is not running the documentation job after completing testing, which is what it should do (and used to do). Nothing has changed significantly as far as I am aware in the config file so this may be a change on travis' end. Will update here with any more info as I find it.

**Comment by moustachio-belvedere** [comment]
Dev version now seems to be updating fine. Note when you push that there are now 7 jobs. 6 for testing each version of Julia on different operating systems and 1 called 'documentation' which builds the dev docs. Working on stable now.

**Comment by moustachio-belvedere** [comment]
Closing this for now in favour of https://github.com/JuliaRheology/RHEOS.jl/issues/70 as doc build is likely not going to be in separate github actions the issues have too much overlap, essentially duplicates.
