### ISSUE TITLE
Strange bug when using mittleff + function wrappers

### ISSUE THREAD

**Issue by moustachio-belvedere** [JuliaRheology/RHEOS.jl#61]
Julia v1.3.1 on Windows, 64 bit build.

Very difficult to pin down as it happens sometimes and doesn't happen other times, no pattern that I could discern. Here's the test script I am using:

https://gist.github.com/moustachio-belvedere/767ad779f1ee1f286615b20aa445dc11

Perhaps someone could try it on Linux?

**Comment by moustachio-belvedere** [comment]
I've reduced this down to a simpler problem.

https://gist.github.com/moustachio-belvedere/a8eca69b24b3b75e9b2c2f25b9daf91b

Walking through separate cases:

1st case, trying mittag leffler in function wrapper, it doesn't work on first run and then works subsequently.

2nd case, just simple function wrapper example works fine

3rd case, simple function wrapper with a call to another julia function works fine

4th case, function wrapper with call to gamma function (which uses c calls) works fine

5th case, function wrapper with call to erfc function works fine

6th case, function wrapper with a quadgk integral breaks as with 1st case (doesn't work first time and works subsequently.)

Note that I tested erfc, gamma and quadgk functions as these are the only three functions that mittleff calls out to so I wanted to see if the error was caused by mittag leffler dependencies or mittag leffler itself.

Having done that, it looks like the issue is combining quadgk with functionwrappers. `mittleff` uses quadgk and that is why we're getting the error.

I don't understand yet why quadgk and functionwrappers aren't getting along but will investigate further.

**Comment by moustachio-belvedere** [comment]
This could be a messy problem as quadgk uses LinearAlgebra.jl and DataStructures.jl, I'm not sure how those two packages are structured and how they might make special use of ccalls etc. 

A bug report may be required on one of the packages or Julia itself but I'm not even sure where it belongs right now (if anywhere).

At the moment I think our options are:

- Figure out underlying issue, report bugs as necessary and wait it out

- Remove function wrappers (which has its own drawbacks)

As a last hopeful shot in the dark I'm going to try download Julia 1.4 release candidate 1 and see if the issue is fixed there.

**Comment by moustachio-belvedere** [comment]
Testing on Julia 1.4 has only further confused me.

On 1.4 case 6 works fine first time round, now the bug is only triggered by case 1.

Leaving this for now so that we can discuss options.

**Comment by moustachio-belvedere** [comment]
So this is all recorded in one place:

I posted an issue about our function wrappers bug and the creator (who is also a core Julia developer) got back to me.

https://github.com/yuyichao/FunctionWrappers.jl/issues/12

It looks like it is a Julia compiler bug with an issue that has been open for a long time.

https://github.com/JuliaLang/julia/issues/28669

**Comment by akabla** [comment]
In branch FWfix, I have fixed the problem by bypassing the array versions of the relaxation and creep moduli. In 1.4.1, mittleff within a function wrapper is fine, but broadcasting an array causes a crash. So new functions were defined in definitions.jl to provide functions on array based on the scalar versions. Optimisation functions in processing.jl were changed accordingly.

For now all the tests are passed...
We now need to check that there is no significant performance issue as a result and consistently change the test code to use Ga(m) and Ja(m). So far, I only updated the sections using the mittleff function.

**Comment by moustachio-belvedere** [comment]
Might be good to have somewhere to keep track of discussion on this for when the development status of function wrappers becomes clearer in the future, don't mind if it is in an open new issue or just informal discussion though.

**Comment by akabla** [comment]
I'm reopening it and assigning to v 1.0.0.

Louis, you are right that we need to keep this open and check on a regular basis.

Julia 1.5 will have a new feature to report bugs, so whenever 1.5 is out we can test it again and report issues properly to the julia developers.

[Julia 1.5 Feature Preview: Time Traveling (Linux) Bug Reporting ](https://julialang.org/blog/2020/05/rr/)

**Comment by moustachio-belvedere** [comment]
Nightly builds suddenly started working after my minor documentation fix yesterday. I didn't touch any source code so something has changed on Julia end.

Looking at the relevant issues again it seems that this may have been fixed whilst developers where fixing an adjacent issue:

https://github.com/JuliaLang/julia/issues/28669

https://github.com/JuliaLang/julia/issues/39804

https://github.com/JuliaLang/julia/pull/39821

**Comment by akabla** [comment]
I removed the GA_safe flag on the Fract Mxawell models on the dev branch, after updating my packages, using julia 1.6.
The tests are being passed just fine. So it looks like the issues with FW are now resolved indeed. 6faf1658110166068f2e0affcb48b036b143cd83

Let's do a bit more testing before rushing to the conclusion though.

**Comment by akabla** [comment]
Sorted with Julia 1.6.
Removed all flags with this PR: #108
