### ISSUE TITLE
Remove MittagLeffler.jl from deps

### ISSUE THREAD

**Issue by moustachio-belvedere** [JuliaRheology/RHEOS.jl#62]
MittagLeffler.jl is now available on the central Julia package repository so we could probably move it from the deps folder and include it in the Project.toml file instead so that the correct version is automatically installed when users install RHEOS.

I'm happy to do this but I can't remember if we made any changes to our version of `mittleff` to accomodate boundaries on parameters? Will have a look now but let me know if you have any thoughts. 

Edit: there is a small change in our version, this requires more than just swapping out for the central package repository version.

**Comment by moustachio-belvedere** [comment]
I think I remember a bit more about this now, writing here so it is not missed when we come to remove MittagLeffler as an internal dependency.

Having a large 'cost' trigger when the mittag-leffler argument `a>1` (or beta, doesn't matter) is handy because it puts a natural limit on coefficients (of single-springpot models at least) without having to specify this explicitly as a bound on the optimiser. It's not straightforward for RHEOS to recognise this without being told as there is no special field which tells RHEOS that the model in use is fractional and must have certain constraints during fitting. The situation is more complicated with 2+ springpot models. There is interesting room here to explore ways of imposing the various parameter inequalities that are required for some fractional models within RHEOS. If we can't find a nice way to implement in code, we could at least mention in documentation. (E.g. issues discussed with Noam when he was fitting data.)

**Comment by akabla** [comment]
If I understand properly, the only change we need compared to the default MittagLeffler.jl library is to return a large value when alpha is equal or less to 0 (line 173 in our fork of the repo). We could probably use the library from the central repo and simply have a wrapper function to test alpha first, and then either return a large value or call the mittleff function. That would allow us to keep up to date with the mittleff package. Given the size of the mittleff computation, that should not be a significant overhead at all.

Any views?

**Comment by moustachio-belvedere** [comment]
Sounds good to me. Although MittagLeffler.jl is rarely updated. In fact, if I remember correctly one of the reasons I made it an embedded dependency in the first place was because it didn't have a Project.toml for some time and so didn't play nicely with the new Julia package manager:

https://github.com/jlapeyre/MittagLeffler.jl/issues/6 

As the Project.toml doesn't seem to be updated very often, we should check that its `[compat]` section doesn't cause any conflicts with other packages we need different versions of (i.e. QuadGK and SpecialFunctions).

It would be nice for it to be removed as an embedded dep to keep RHEOS repo clean, and I like your approach of having a wrapper function :+1: 

Yes, I had a look at the history/gitblame of the file:

https://github.com/JuliaRheology/RHEOS.jl/blame/master/deps/MittLeffLite/MittLeffLite.jl

and can confirm 173 is the only line Ale changed. In fact, here's the exact change made:

https://github.com/JuliaRheology/RHEOS.jl/commit/78a5b31c1d06b9e2fa94a2a0af945edefa64124f#diff-5ec7d9b801251281e926bebf0e96e487a7b764a4528375f09b451b9ac6685f5b

**Comment by moustachio-belvedere** [comment]
I looked into the dependencies issue, it seems that the only place we use QuadGK is from within mittleff itself so that's not a problem. 

We use SpecialFunctions in a few test functions, but it's a pretty standardised library. It shouldn't cause us problems in that context, but other libraries we use that are more regularly updated may request a more up to date version of SpecialFunctions. That's the only issue I can foresee right now.

We can always create an issue on the repo, requesting an upgrade to dependencies, but it might take some time to get a response.

**Comment by akabla** [comment]
OK, let's try to do this in the near future then, it should not be too onerous. It's on my list now!
I guess we should at the same time remove QuadGK for our deps and let it come alongside LittagLeffler.jl?

For SpecialFunctions, let's see. Hopefully, all will be fine, but I appreciate it can be a problem indeed.

**Comment by moustachio-belvedere** [comment]
Sounds great. Yep we can get rid of (explicit) QuadGK dependency at the same time!

**Comment by akabla** [comment]
We use the gamma function in RHEOS in base.jl and other functions.

It is imported from SpecialFunctions in the MittagLeffler code embedded in RHEOS, but not otherwise, so if/when we drop the MittagLeffler code from RHEOS and import it from the main repo, we will need to import it again in RHEOS.jl.

**Comment by akabla** [comment]
As I was constructing benchmarks for the current version of Rheos, I hit some difficulties getting sensible performance for relaxation function of the FractSLS_Zener model. Nothing consistent with [Louis' benchmarks](https://github.com/JuliaRheology/RheoBenchAndTest/blob/master/20210410_fwclosures_additional.jl).

I pulled my hair for a couple of hours with this, only to narrow it down to the fact that RHEOS uses mittleff as an embedded dependency, and is not using the version on the central repo. Turns out that it makes a massive difference. Check this benchmark code:

```
using RHEOS
using BenchmarkTools
using MittagLeffler

t=RheoFloat.(0.0:0.001:1.0);
t0=1.0
t=RheoFloat.(0.0:0.001:1.0);

println()
println("Test on the MittalgLeffler function")
println()
cₐ = 1.0; a=0.5; kᵦ = 2.0; kᵧ=3.0
println("Imported library")
@btime kᵦ*RHEOS.mittleff(a, -(kᵦ/cₐ)*t0^a) + kᵧ
@btime kᵦ.*RHEOS.mittleff.(a, -(kᵦ./cₐ).*t.^a) .+ kᵧ;
println("Version from Julia repo")
@btime kᵦ*mittleff(a, -(kᵦ/cₐ)*t0^a) + kᵧ
@btime kᵦ.*mittleff.(a, -(kᵦ./cₐ).*t.^a) .+ kᵧ;
println("Test on the FractSLS_Zener model")
@btime relaxmod(FractSLS_Zener, t0, [1.0,0.5,2.0,3.0])
@btime relaxmod(FractSLS_Zener, t, [1.0,0.5,2.0,3.0]);

println("Checking values are consistent")
println(kᵦ*mittleff(a, -(kᵦ/cₐ)*t0^a) + kᵧ)
println(kᵦ*RHEOS.mittleff(a, -(kᵦ/cₐ)*t0^a) + kᵧ)
println(relaxmod(FractSLS_Zener, t0, [1.0,0.5,2.0,3.0]))
```

which gives this output:
```
Imported library
  7.822 μs (227 allocations: 3.98 KiB)
  22.107 ms (185098 allocations: 3.17 MiB)
Version from Julia repo
  213.558 ns (7 allocations: 112 bytes)
  67.817 μs (15 allocations: 8.53 KiB)
Test on the FractSLS_Zener model
  7.723 μs (221 allocations: 3.98 KiB)
  22.006 ms (185086 allocations: 3.17 MiB)
Checking values are consistent
3.5107913526210117
3.5107913526210117
3.5107913526210117
```

I guess we need to get rid of the embedded deps as soon as possible. Everything else looks like a pointless refinement at this stage!

**Comment by akabla** [comment]
I quickly tweaked RHEOS.jl to include the external package, commented out the inclusion of the local version, and...

```
Version from Julia repo
  209.245 ns (7 allocations: 112 bytes)
  68.591 μs (15 allocations: 8.53 KiB)
Test on the FractSLS_Zener model
  142.541 ns (2 allocations: 128 bytes)
  64.394 μs (3 allocations: 8.16 KiB)
```
That's more like what I expected!

**Comment by moustachio-belvedere** [comment]
Nice work on finding that.

It seems there were five mittleff commits since we brought it in as embedded dep, two of which may be related:

https://github.com/jlapeyre/MittagLeffler.jl/commit/b446db7b657e714faaa52d60d95e323c63f52853
https://github.com/jlapeyre/MittagLeffler.jl/commit/41f4964e6959f456da3661f04d4a81475d4a330b

Probably the second one. I'd be curious to know what he meant by this comment:

https://github.com/jlapeyre/MittagLeffler.jl/commit/41f4964e6959f456da3661f04d4a81475d4a330b#diff-6ca63c187a872a5d283e5a9c36848d3f55dfa043d7e10f0d99e5cc6a1620b6f1R93

>  The effect on the accuracy is not controlled.

Regardless, nice detective work!

**Comment by akabla** [comment]
Not sure either about the comment on accuracy. Well, we'll have to trust the author!
Interesting that he says the gamma function comes from GSL. I guess that happens through SpecialFunctions.
