### ISSUE TITLE
Define moduli functions that are safe for the user and well documented

### ISSUE THREAD

**Issue by akabla** [JuliaRheology/RHEOS.jl#65]
I think we should make the moduli functions m.G, m.Ga, m.J, etc internal and create user-friendly methods to access them, except internally in Rheos where efficiency matters.

Proposal:
- If m::RheoModel

relaxmod(m,t) --> m.G(t)
relaxmod(m,a) --> Ja(m)(t)
relaxmod(m) returns a function calling m.G or _Ga(m) depending on the type of its input:
    relaxmod(m) = x -> relaxmod(m,x)

- If m::RheoModelClass

relaxmod(m, t; kwa...)
relaxmod(m, a ; kwa...)
relaxmod(m; kwa...)

Other moduli:   creepmod(), dynamicmod()  --> complex array by default, storagemod and lossmod for real and imaginary parts.

I think we need longer and explicit names since symbols G and J may clash with other libs and user codes.

I also propose to rename the FW functions into something less user friendly (e.g. m._G and _Ga() ) to show that these are designed as internal functions.

The test functions would only use the user level functions so that we don't need to export _Ga and _Ja.

So far in the doc we haven't used these functions much.

**Comment by moustachio-belvedere** [comment]
I agree this is nice, but worth considering, if in the (very) long term, the functionwrappers library issue is not resolved and we decide go down the keyword arguments route for moduli we may not need these? (if there main advantage is being able to call using keyword arguments for parameters)

**Comment by akabla** [comment]
Thanks Louis.

Regardless of the function wrapper issue, I think it is not really in the spirit of julia to have something that looks like an OO member function, so I'd keep the functions above as the documented approach. This also protects us from making changes that would break user code when we resolve the function wrapper situation one way or another. Since the moduli function would take keyword arguments already, it would make it even easier. Do you agree Louis?

**Comment by moustachio-belvedere** [comment]
Yes that makes sense, so if we do eventually go KW route the above functions can simply be a thin wrapper on top of them. Eitherway, I like the plan! The less OO methods lookalike the better :+1:

**Comment by akabla** [comment]
Great, we got a plan then! I'll deal with it in the next few days I think. We have a new dev branch, so I'll be there.

**Comment by akabla** [comment]
Working on this, I realised that I am not naming properly J. The creep modulus should be 1/J, and obviously have the unit of a pressure! It seems that J should be called creep compliance (or compliance function, but I don't like that name as it makes no reference to creep...). 

1. Are we OK to rename creepmod as creepcomp?
2. Do we have a need for a function creepmod that returns 1/J? My guess is no.

**Comment by moustachio-belvedere** [comment]
I often use creep modulus/compliance interchangebly, didn't even consider it, but yes seems like the right move to use `creepcomp` instead of `creepmod`!

https://www.oxfordreference.com/view/10.1093/acref/9780198832102.001.0001/acref-9780198832102-e-1193?rskey=Z5oDSc&result=19

and yes, i agree with you that we don't need a 1/J function.

**Comment by akabla** [comment]
OK, thanks. done.
