### ISSUE TITLE
Add contributing section to docs

### ISSUE THREAD

**Issue by moustachio-belvedere** [JuliaRheology/RHEOS.jl#72]
Decide on protocol for working on features and releases and document it

**Comment by akabla** [comment]
Hi Louis, have you seen good examples of such protocols in other packages?

**Comment by moustachio-belvedere** [comment]
I think we have probably decided on things now like semantic versioning, branch structure, so it's a question of writing that down. But also expected etiquette like 'don't just pull a request a large feature addition or change without starting an issue first so it can be discussed' (in more polite terms). And perhaps a style guide so the code doesn't start becoming a higgledy-piggledy mess. This is a good example:

https://juliadocs.github.io/Documenter.jl/dev/contributing/

Will post other examples here as I find them.

**Comment by moustachio-belvedere** [comment]
This one is much briefer, just a short paragraph at the end of the Readme. Perhaps something like that is more appropriate:

https://github.com/korsbo/Latexify.jl

This developer reference is nice. I also like that they call their API section 'user reference' which is probably friendlier than API for the uninitiated:

https://timholy.github.io/Revise.jl/stable/dev_reference/

**Comment by moustachio-belvedere** [comment]
@akabla Am I right in thinking that we seem to have settled on:

- Create a branch for a new feature
- Work on that branch
- When feature is complete, merge via pull request within GitHub
- If tests pass, everyone happy, accept pull request
- When milestone features are implemented, we register a new stable version

This should be quite quick to document, I'm happy to do it so we can resolve this issue.

However, I'm wondering if it should go in the main RHEOS documentation or in the https://github.com/JuliaRheology/RheoHelpDocs metadocumentation?

Let me know what you think. Happy to have a more involved discussion if needed.

**Comment by moustachio-belvedere** [comment]
Done https://github.com/JuliaRheology/RHEOS.jl/commit/cf1738629aa7672df3e272d1436491e817bbc087
