### ISSUE TITLE
Set workflow to manage compat list on Project.toml

### ISSUE THREAD

**Issue by akabla** [JuliaRheology/RHEOS.jl#76]
We may find CompatHelper helpful for keeping your compat entries up-to-date.
https://github.com/bcbi/CompatHelper.jl

How to do it otherwise? 
Maybe:
Remove compat list from Project.toml
pkg> activate .    (in Rheos directory)
pkg> up    (to update all packages)
run all tests
pkg> st     (to list the version of all packages)

--> put it back in Project.toml

**Comment by moustachio-belvedere** [comment]
Sounds good to me. Should we make a note of that and then close the issue? Maybe somewhere in:
 
https://github.com/JuliaRheology/RheoHelpDocs

**Comment by moustachio-belvedere** [comment]
This is now included in the file https://github.com/JuliaRheology/RheoHelpDocs/blob/master/VersioningGuide.md

I have also updated all the other files (testing and documentation meta-documentation) to reflect the new GitHub actions workflow.
