### ISSUE TITLE
rename RheoTimeDataType & RheoFreqDataType

### ISSUE THREAD

**Issue by akabla** [JuliaRheology/RHEOS.jl#80]
These are functions, and should not have capital letters for consistency with Julia style.

**Comment by moustachio-belvedere** [comment]
I can see some options here:

1) we just rename the functions to `rheotimedatatype` and `rheofreqdatatype` respectively.

2) we make `RheoTimeData` and `RheoFreqData` abstract types, and the subtype with concrete types that correspond to each of the different possible enumerations.

Unfortunately we can't just methods to `typeof` as it is a restriction of Julia and causes an error. So, solution 1 is probably the most straightforward. However, solution 2 _might_ (I don't know) be a bit more idiomatic Julia. I don't have a strong preference either way.

**Comment by moustachio-belvedere** [comment]
As discussed @akabla @ab2425 we will go for option 1.

**Comment by moustachio-belvedere** [comment]
Resolved in commit https://github.com/JuliaRheology/RHEOS.jl/commit/eca00b973d9775303f7de1242f780af37d69d775
