### ISSUE TITLE
Move from Travis to Github Actions

### ISSUE THREAD

**Issue by moustachio-belvedere** [JuliaRheology/RHEOS.jl#92]
The case in favour of migrating from Travis CI to Github actions for testing and documentation building has recently got much stronger. Travis has been taken over by a private equity company and appears to no longer be providing free server time to open source projects. For discussion, see for example:

https://news.ycombinator.com/item?id=25338983

https://news.ycombinator.com/item?id=19219216

We have two options:

- A brave person can try and figure out how to migrate our current documentation and test system to github actions (I  tried to do this unsuccessfully over summer 2020, it's quite frustrating and I would be happy for someone else to give it a try).

- We can take the jump to using Literate.jl package, which means Github actions are much easier to setup. See for example the demo package I made (https://github.com/moustachio-belvedere/JuliaPackageDemo.jl).

If we do nothing, we will no longer be testing on push-to-github, and documentation updates will not be built. Of course, this change to Travis policy may be highly unpopular and they may backtrack, but it seems unwise to rely on that.

**Comment by akabla** [comment]
Hi Louis,

you are right, this needs to be addressed.
I think switching to Literate.jl is a very good approach. I love what you did, but that is a significant task too.

Another topic for discussion in the next few weeks!

**Comment by moustachio-belvedere** [comment]
This seems to be working nicely now on my test repository. It has testing, documentation and code coverage all done by a Github action. And it updates the badge on the README.

https://github.com/moustachio-belvedere/JuliaPackageDemo.jl/blob/master/.github/workflows/CI.yml

I'll create a new branch and start converting the documentation to Literate.jl soon -- https://github.com/JuliaRheology/RHEOS.jl/tree/literatedocs

**Comment by moustachio-belvedere** [comment]
Checklist in case others want to contribute, though I'm happy to keep working on it slowly over the next few days:

- [x] Home
- [x] Architecture
- [x] File I/O
- [x] Preprocessing
- [x] Generating Data
- [x] Fit and Predict
- [x] Models
- [x] Examples
- [x] API

**Comment by akabla** [comment]
Thanks Louis for all this! Hopefully I'll get my head around this before the start of term.

**Comment by moustachio-belvedere** [comment]
No worries, happy to discuss any time!

**Comment by moustachio-belvedere** [comment]
Making note of the issue for future reference, the only feature from Literate.jl that is missing for us is inline math mode. For now I've just replaced the small number of inline math portions with their direct unicode equivalent. We can always change this in future once the capability is added to Literate.jl.

https://github.com/fredrikekre/Literate.jl/issues/116

**Comment by moustachio-belvedere** [comment]
Apologies, was a bit of a mess as I made the first pull request too quickly before seeing that the documentation wasn't building properly. I then reverted the pull request, so that I could fix the remote documentation build, and then reverted the first revert of the pull request.

Anyway, after a slightly stressful hour or two, it seems to have built fine and is working. 

Binder won't be working just yet as I need to add a Project.toml file the gh-pages branch, but the notebook viewer seems to be working fine.

**Comment by moustachio-belvedere** [comment]
For reference, added Julia dependencies for binder in Project toml on gh-pages branch, and matplotlib in Python requirements.txt in commits https://github.com/JuliaRheology/RHEOS.jl/commit/af920e19c34a73a85111378406d7c68304fc23b4 and https://github.com/JuliaRheology/RHEOS.jl/commit/fefcd5e73ff5ff8fd12ce0a5c238ba7766f2cd42

The interactive notebooks seem to be working well.
