### ISSUE TITLE
Resample function needs to be organised, tested, documented

### ISSUE THREAD

**Issue by moustachio-belvedere** [JuliaRheology/RHEOS.jl#93]
When I was transferring the current documentation to Literate.jl branch today, there were some errors as the docs were using the old implementation of resample.

I noticed that there is still an old version of resample commented out in `src/processing.jl` and there are also some tests commented out. The docstring for the new resample function just says 'resamples data' with a couple of usage examples so, whilst I remember roughly what we discussed in various chats, I needed to look at the code itself to properly figure out what was going on.

I don't mind what the resample function actually does, I think I'm happy with what we discussed before, but we need to remove old versions of it (and tests of the old version) from all source code and make sure it is documented. 

**Edit**: for now I'm making a temporary fix in the preprocessing section of the documentation as I want to get as much of the docs transfer done as quickly as possible (issue https://github.com/JuliaRheology/RHEOS.jl/issues/92), but that page will need to be looked at again.

**Comment by akabla** [comment]
Thanks Louis. I'm certainly guilty here! I'll try to look at it soon.

**Comment by moustachio-belvedere** [comment]
No problem, sounds good! It should be easier to update the docs once everything is using Literate anyway.

**Comment by moustachio-belvedere** [comment]
Whilst updating the license, I was also looking at docstrings etc, took the opportunity to remove the old version of resample from source code to neaten things up (everything that was commented out). We can remove the other bits e.g. outdated tests, later on.

6e58ab0684bd3997483810f1c45ff5051656192a is commit hash.

**Comment by akabla** [comment]
@ab2425 @moustachio-belvedere 
There is a fixedresample function commented out in base.jl. Can this one go too?

It looks like the resample function in processing.jl is sufficiently commented. Anything missing? Otherwise we can close this one I think.

**Comment by moustachio-belvedere** [comment]
Yep the one in base can go too.

On docstring, it's good enough for us (You, Ale and me), but for public consumption I think it needs more work. The parts that stand out immediately: description of the function is pretty bare, uses single quotemarks for syntax instead of backticks (this ends up being formatted incorrectly in the HTML documentation). 

Also, it doesn't follow the docstring guidelines (usage section is not idiomatic, use initial explanation paragraph, arguments section if necessary, and an examples block). This is a slightly wider issue in RHEOS we should try to be more consistent with, which is why I created this the other day so I remember to make changes as and when I see them

https://github.com/JuliaRheology/RHEOS.jl/issues/101

Julia link https://docs.julialang.org/en/v1/manual/documentation/

Apologies if the above seems over pedantic. In the case of one function, it **is** over pedantic. But if all functions in RHEOS end up having a different docstring convention then things will really get messy.

Also, if we subscribe to standard Julia convention it makes things much smoother if other people want to contribute to RHEOS in the future, as we have a universal standard with which to assess pull requests.

**Comment by moustachio-belvedere** [comment]
Also, on closing the issue:

I think the documentation itself needs a read-through from you if you haven't done so already because you're most on-top of this function? As I was rushing through trying to get things converted to the new docs format there may be some outdated explanations in there. In particular, this page:

https://juliarheology.github.io/RHEOS.jl/dev/preprocessing/

but maybe some of the other pages too, I can't remember where resampling comes up in other sections.

Last one to get it closed is testing, are you happy the function is sufficiently tested for all use cases? There are still commented out tests from the old resample function.

**Comment by moustachio-belvedere** [comment]
A side point related to this as we were discussing pull requests yesterday. In my opinion, this is where keeping commits focused and adding them into RHEOS.jl via pull requests really shines as a workflow. It would allow me, or anyone else, to quickly see all code changes associated with this issue.

**Comment by moustachio-belvedere** [comment]
Two examples that I consider more complete:

https://github.com/JuliaRheology/RHEOS.jl/blob/master/src/definitions.jl#L587

https://github.com/JuliaRheology/RHEOS.jl/blob/master/src/processing.jl#L322

But even those could be improved to adhere more closely to Julia docstring guidelines.

**Comment by akabla** [comment]
Hi Louis,

Indeed, there are some formatting issues - not very visible on a text editor, but it does make a difference online. I'll fix that. I'm happy to reformat the doc according to the Julia guidelines too. You're a tough cookie Louis! :-)

I won't do a full read-through of the docs as I won't have time to fix them properly anyway if needed. So let's continue to address things as they show up. All this is in good progress overall.

Yes, tests are fine on this function. I considered most of the data types and input types, so I think it covers quite well already the different use cases. I'll delete the commented-out bits in base.jl and in the tests. Just wanted to check all can go indeed. 

PR to follow later today.

**Comment by akabla** [comment]
Closing as good enough for now. The general consistency of the doc API remains a problem to address progressively.
